logging:
  level:
    ROOT: DEBUG
    com.microservices.demo: DEBUG

spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  config:
    import: 'configserver:'
  cloud:
    config:
      # all'interno del config-server-repository abbiamo il file config-client-elastic_query_web
      name: elastic-query-web-client,config-client
      username: spring_cloud_user
      password: ${SPRING_SECURITY_USER_PASSWORD}

log:
  app-name: elastic-query-service