logging:
  level:
    ROOT: INFO
    com.microservices.demo: INFO
    org.spring.framework.cloud.config: INFO

spring:
  application:
    name: elastic-query-service
  profiles:
    active: elastic_query
  config:
    import: 'configserver:'
  cloud:
    config:
      # all'interno del config-server-repository abbiamo il file config-client-elastic_query
      name: elastic-query-service,config-client
      username: spring_cloud_user
      password: ${SPRING_SECURITY_USER_PASSWORD}

log:
  app-name: elastic-query-service