version: '3.7'
volumes:
  postgres_data:
    driver: local
  pgadmin-data:
    driver: local

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=secret"
      - "PGADMIN_LISTEN_PORT=80"
    ports:
      - "9000:80"
    depends_on:
      - postgres
    networks:
      - ${GLOBAL_NETWORK:-postgres}
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - "9001:8080"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_LOG_LEVEL=INFO"
      - "KC_DB=postgres"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=password"
      - "KC_DB_SCHEMA=keycloak"
      - "KC_DB_URL_DATABASE=keycloak"
      - "KC_DB_URL_HOST=postgres"
    depends_on:
      - postgres