version: '3.7'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=keycloak"
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5433:5432"
    networks:
      - ${GLOBAL_NETWORK:-postgres}

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=secret"
      - "PGADMIN_LISTEN_PORT=80"
    ports:
      - "9000:80"
    depends_on:
      - postgres
    networks:
      - ${GLOBAL_NETWORK:-postgres}

volumes:
  postgres_data:
    driver: local
  pgadmin-data:
    driver: local