spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic
  config:
    import: 'configserver:'
  cloud:
    config:
      # all'interno del config-server-repository abbiamo il file config-client-kafka_to_elastic
      name: kafka-to-elastic-service,config-client
      username: spring_cloud_user
      password: ${SPRING_SECURITY_USER_PASSWORD}

log:
  app-name: kafka-to-elastic-service