server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: INFO

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apanzani/spring-cloud-config-server-repository
          username: apanzani
          password: '{cipher}09da987aa97a244ea07fba6c67bb4f8ee00d8049cee6e4319ade1da689f3a5a837d5a57d7f66dbde70ccc106e0b3e534424286a50debf32cb69e0ee06fdec140'
          default-label: main
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: ${SPRING_SECURITY_USER_PASSWORD}
log:
  app-name: config-server